name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/adedeji-portfolio:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/adedeji-portfolio:latest

    - name: SSH into EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to Minikube
      run: |
        minikube start
        kubectl config use-context minikube
        kubectl apply -f k8S/deployment.yaml 
        kubectl apply -f k8S/service.yaml 
      shell: bash
      continue-on-error: true

    - name: Verify Deployment
      run: |
        kubectl get deployment
        kubectl get svc
      shell: bash
      continue-on-error: true
